SUPABASE_URL="https://eiiwfizxtoelfhsmqxgs.supabase.co"

SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpaXdmaXp4dG9lbGZoc21xeGdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUyMjI5NzUsImV4cCI6MjEwMDc5ODk3NX0.c3ylZyuOR1pIDLm7m3tI2ttzcB1rauyn4-pLwKV1vSU"
