from supabase import create_client
import streamlit as st

SUPABASE_URL = st.secrets["https://eiiwfizxtoelfhsmqxgs.supabase.co"]
SUPABASE_KEY = st.secrets["sb_publishable_DDrxVpjTSS6hsGnhyJM5Dw_klVutw2C"]

supabase = create_client(
    SUPABASE_URL,
    SUPABASE_KEY
)
